//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDemo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int InputChannels {
            get {
                return ((int)(this["InputChannels"]));
            }
            set {
                this["InputChannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int OutputChannels {
            get {
                return ((int)(this["OutputChannels"]));
            }
            set {
                this["OutputChannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SamplingRateIndex {
            get {
                return ((int)(this["SamplingRateIndex"]));
            }
            set {
                this["SamplingRateIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowingIndex {
            get {
                return ((int)(this["WindowingIndex"]));
            }
            set {
                this["WindowingIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FunctionIndex {
            get {
                return ((int)(this["FunctionIndex"]));
            }
            set {
                this["FunctionIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int FFTLinesIndex {
            get {
                return ((int)(this["FFTLinesIndex"]));
            }
            set {
                this["FFTLinesIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Averages {
            get {
                return ((int)(this["Averages"]));
            }
            set {
                this["Averages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1031")]
        public decimal OutputFrequency {
            get {
                return ((decimal)(this["OutputFrequency"]));
            }
            set {
                this["OutputFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0")]
        public decimal OutputAmplitude {
            get {
                return ((decimal)(this["OutputAmplitude"]));
            }
            set {
                this["OutputAmplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int SpectraMax {
            get {
                return ((int)(this["SpectraMax"]));
            }
            set {
                this["SpectraMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int SpectraDecades {
            get {
                return ((int)(this["SpectraDecades"]));
            }
            set {
                this["SpectraDecades"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int OutputSignalTypeIndex {
            get {
                return ((int)(this["OutputSignalTypeIndex"]));
            }
            set {
                this["OutputSignalTypeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputWaveFileName {
            get {
                return ((string)(this["OutputWaveFileName"]));
            }
            set {
                this["OutputWaveFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InputWaveFileName {
            get {
                return ((string)(this["InputWaveFileName"]));
            }
            set {
                this["InputWaveFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5.72")]
        public decimal FullScaleInput {
            get {
                return ((decimal)(this["FullScaleInput"]));
            }
            set {
                this["FullScaleInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.5")]
        public decimal FullScaleOutput {
            get {
                return ((decimal)(this["FullScaleOutput"]));
            }
            set {
                this["FullScaleOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int _BufferSizeIndex {
            get {
                return ((int)(this["_BufferSizeIndex"]));
            }
            set {
                this["_BufferSizeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<gcxDocument version=\"17.0\">\r\n  <gcxData>\r\n    <GCXCTRL sizeExtent_x=\"13414\" size" +
            "Extent_y=\"10345\" designTimeSaved=\"0\" graphLayers=\"1\"/>\r\n    <GRAPH_GDI state=\"0\"" +
            " viewports=\"1\" major_h=\"1\" major_v=\"1\" minor_h=\"0\" minor_v=\"0\">\r\n      <cursor n" +
            "ame=\"Main\" visible=\"1\" active=\"1\" align=\"1\" color=\"4718664\" hot=\"0\" style=\"0\" co" +
            "lor2=\"16777215\"/>\r\n      <Main horizontal_line=\"1\" tacho_identification=\"1\"/>\r\n " +
            "     <cursor name=\"Delta\" visible=\"0\" active=\"0\" align=\"1\" color=\"65535\" hot=\"0\"" +
            " style=\"0\" color2=\"16777215\"/>\r\n      <Delta tacho_identification=\"1\"/>\r\n      <" +
            "cursor name=\"Reference\" visible=\"0\" active=\"0\" align=\"1\" color=\"2263842\" hot=\"0\"" +
            " style=\"0\" color2=\"16777215\"/>\r\n      <Reference horizontal_line=\"1\" tacho_ident" +
            "ification=\"1\"/>\r\n      <cursor name=\"Marker1\" visible=\"0\" active=\"0\" align=\"1\" c" +
            "olor=\"5275647\" hot=\"0\" style=\"0\" color2=\"16777215\"/>\r\n      <cursor name=\"Marker" +
            "2\" visible=\"0\" active=\"0\" align=\"1\" color=\"17919\" hot=\"0\" style=\"0\" color2=\"1677" +
            "7215\"/>\r\n      <cursor name=\"Harmonic\" visible=\"0\" active=\"0\" align=\"1\" color=\"2" +
            "237106\" hot=\"0\" style=\"0\" color2=\"16777215\"/>\r\n      <Harmonic show_all_frequenc" +
            "ies=\"1\" harmonic_count=\"10\"/>\r\n      <cursor name=\"Sideband\" visible=\"0\" active=" +
            "\"0\" align=\"1\" color=\"3618615\" hot=\"0\" style=\"0\" color2=\"16777215\"/>\r\n      <curs" +
            "or name=\"TagCursor\" visible=\"0\" active=\"0\" align=\"1\" color=\"14822282\" hot=\"0\" st" +
            "yle=\"0\" color2=\"16777215\"/>\r\n      <TagCursor NextUniqueID=\"1001\" SearchSensitiv" +
            "ity=\"1.5\" SearchHalfWidth=\"9\" SearchMaximumExtremaCountWanted=\"0\" LevelFilterEna" +
            "bled=\"0\" LevelFilterValue=\"0\" TagsortMode=\"1\" TagCursorInfoListCount=\"0\"/>\r\n    " +
            "  <view name=\"Default area\" state=\"16\" header=\"0\" text=\"static text\" complexEnab" +
            "led=\"0\" secondaryViewportEnabled=\"0\" secondaryViewportAtBottom=\"1\" percentageTop" +
            "Subviewport=\"50\" secondaryCoordinateIsPhase=\"0\" secondaryViewportAtBottom_IfPhas" +
            "e=\"0\" percentageTopSubviewport_IfPhase=\"30\" nyquistIsSquare=\"0\"/>\r\n    </GRAPH_G" +
            "DI>\r\n    <XAXIS state=\"0\" unit=\"\" title=\"\" type=\"0\" zoomStart=\"0\" zoomStop=\"1000" +
            "00\" min=\"0\" max=\"1\" tickstep=\"0\" fixticks=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=" +
            "\"3\" trailingZeros=\"0\" numFormat=\"1\" minorTicks=\"0\"/>\r\n    <YAXIS state=\"0\" unit=" +
            "\"\" title=\"\" type=\"5\" zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" t" +
            "ickstepSecondary=\"30\" fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"" +
            "20\" useNice=\"1\" activeOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZer" +
            "os=\"0\" numFormat=\"1\" secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\"" +
            " secondaryLockMin=\"0\" secondaryLockMax=\"0\"/>\r\n    <YAXIS_2 state=\"17\" unit=\"\" ti" +
            "tle=\"\" type=\"5\" zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickst" +
            "epSecondary=\"30\" fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" u" +
            "seNice=\"1\" activeOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0" +
            "\" numFormat=\"1\" secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" seco" +
            "ndaryLockMin=\"0\" secondaryLockMax=\"0\"/>\r\n    <YAXIS_3 state=\"17\" unit=\"\" title=\"" +
            "\" type=\"5\" zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSec" +
            "ondary=\"30\" fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNic" +
            "e=\"1\" activeOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" num" +
            "Format=\"1\" secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondary" +
            "LockMin=\"0\" secondaryLockMax=\"0\"/>\r\n    <YAXIS_4 state=\"17\" unit=\"\" title=\"\" typ" +
            "e=\"5\" zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondar" +
            "y=\"30\" fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\"" +
            " activeOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numForma" +
            "t=\"1\" secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockM" +
            "in=\"0\" secondaryLockMax=\"0\"/>\r\n    <YAXIS_5 state=\"17\" unit=\"\" title=\"\" type=\"5\"" +
            " zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30" +
            "\" fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" acti" +
            "veOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\"" +
            " secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0" +
            "\" secondaryLockMax=\"0\"/>\r\n    <YAXIS_RIGHT1 state=\"0\" unit=\"\" title=\"\" type=\"5\" " +
            "zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30\"" +
            " fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" activ" +
            "eOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\" " +
            "secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0\"" +
            " secondaryLockMax=\"0\"/>\r\n    <YAXIS_RIGHT2 state=\"17\" unit=\"\" title=\"\" type=\"5\" " +
            "zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30\"" +
            " fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" activ" +
            "eOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\" " +
            "secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0\"" +
            " secondaryLockMax=\"0\"/>\r\n    <YAXIS_RIGHT3 state=\"17\" unit=\"\" title=\"\" type=\"5\" " +
            "zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30\"" +
            " fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" activ" +
            "eOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\" " +
            "secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0\"" +
            " secondaryLockMax=\"0\"/>\r\n    <YAXIS_RIGHT4 state=\"17\" unit=\"\" title=\"\" type=\"5\" " +
            "zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30\"" +
            " fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" activ" +
            "eOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\" " +
            "secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0\"" +
            " secondaryLockMax=\"0\"/>\r\n    <YAXIS_RIGHT5 state=\"17\" unit=\"\" title=\"\" type=\"5\" " +
            "zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30\"" +
            " fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" activ" +
            "eOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\" " +
            "secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0\"" +
            " secondaryLockMax=\"0\"/>\r\n    <ZAXIS state=\"0\" unit=\"\" title=\"\" type=\"0\" zoomStar" +
            "t=\"0\" zoomStop=\"100000\" min=\"-1\" max=\"1\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" t" +
            "railingZeros=\"0\" numFormat=\"1\"/>\r\n    <ZAXIS_2 state=\"17\" unit=\"\" title=\"\" type=" +
            "\"0\" zoomStart=\"0\" zoomStop=\"100000\" min=\"-1\" max=\"1\" lockMin=\"0\" lockMax=\"0\" num" +
            "Digits=\"3\" trailingZeros=\"0\" numFormat=\"1\"/>\r\n    <ZAXIS_3 state=\"17\" unit=\"\" ti" +
            "tle=\"\" type=\"0\" zoomStart=\"0\" zoomStop=\"100000\" min=\"-1\" max=\"1\" lockMin=\"0\" loc" +
            "kMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\"/>\r\n    <ZAXIS_4 state=\"17" +
            "\" unit=\"\" title=\"\" type=\"0\" zoomStart=\"0\" zoomStop=\"100000\" min=\"-1\" max=\"1\" loc" +
            "kMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\"/>\r\n    <ZAXIS" +
            "_5 state=\"17\" unit=\"\" title=\"\" type=\"0\" zoomStart=\"0\" zoomStop=\"100000\" min=\"-1\"" +
            " max=\"1\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\"/>" +
            "\r\n    <TITLE/>\r\n    <OVERALL state=\"0\"/>\r\n    <READOUT state=\"0\" pos=\"0.761364\" " +
            "hideNA=\"1\" allFunctions=\"0\" fullScreen=\"0\" hideSplitter=\"0\">\r\n      <DISPSETUP>\r" +
            "\n        <attr name=\"Cursor values\" isUserText=\"1\" isTagVector=\"0\" bold=\"1\" ital" +
            "ic=\"0\" unique=\"0\"/>\r\n        <attr name=\"X: \" unit=\"xAxis\" isUserText=\"0\" isTagV" +
            "ector=\"0\" bold=\"0\" italic=\"0\" unique=\"0\" key=\"1\"/>\r\n        <attr name=\"Y: \" uni" +
            "t=\"yAxis\" isUserText=\"0\" isTagVector=\"0\" bold=\"0\" italic=\"0\" unique=\"0\" key=\"2\"/" +
            ">\r\n        <attr name=\"Z: \" unit=\"zAxis\" isUserText=\"0\" isTagVector=\"0\" bold=\"0\"" +
            " italic=\"0\" unique=\"0\" key=\"3\"/>\r\n        <attr name=\"y: \" unit=\"yAxis\" isUserTe" +
            "xt=\"0\" isTagVector=\"0\" bold=\"0\" italic=\"0\" unique=\"0\" key=\"32\"/>\r\n        <attr " +
            "name=\"Data Quality : \" attrName=\"Data Quality\" groupName=\"Status\" groupType=\"BKI" +
            "ndexAttributeGroup\" isUserText=\"0\" isTagVector=\"0\" bold=\"0\" italic=\"0\" unique=\"0" +
            "\" dir=\"2\"/>\r\n        <attr name=\"Channel Status : \" attrName=\"Channel Status\" gr" +
            "oupName=\"Status\" groupType=\"BKIndexAttributeGroup\" isUserText=\"0\" isTagVector=\"0" +
            "\" bold=\"0\" italic=\"0\" unique=\"0\" dir=\"2\"/>\r\n      </DISPSETUP>\r\n    </READOUT>\r\n" +
            "    <LAYOUT state=\"0\" fixedId=\"{00000000-0000-0000-0000-000000000000}\" mode=\"1\"/" +
            ">\r\n    <STRFORMAT state=\"0\"/>\r\n    <LEGEND state=\"0\">\r\n      <DISPSETUP>\r\n      " +
            "  <attr attrName=\"title\" groupName=\"Buffers\" groupType=\"BKBuffersAttributeGroup\"" +
            "/>\r\n        <attr attrName=\"name\" groupName=\"Analyzer\" groupType=\"BKAnalyzerAttr" +
            "ibuteGroup\"/>\r\n        <body style=\"19\" delimiter=\" \\ \" moved=\"0\"/>\r\n        <fp" +
            "os x=\"0\" y=\"0\" cx=\"0\" cy=\"0\"/>\r\n      </DISPSETUP>\r\n    </LEGEND>\r\n    <REGION_S" +
            "ELECTOR state=\"0\" enabled=\"0\" left=\"0.3\" right=\"0.7\" low=\"0.7\" high=\"0.3\" format" +
            "=\"3\" commandVisibility=\"526\"/>\r\n    <CurveSmoothing state=\"0\" progid=\"BKCurveSmo" +
            "othing.CurveSmoothing\">\r\n      <CurveSmoothing SmoothingType=\"1\" WindowType=\"1\" " +
            "SmoothingMode=\"1\" Octave=\"1\" Order=\"1\">\r\n        <Markers/>\r\n      </CurveSmooth" +
            "ing>\r\n    </CurveSmoothing>\r\n    <ReferenceCurve/>\r\n    <GCXDROP state=\"0\"/>\r\n  " +
            "</gcxData>\r\n</gcxDocument>\r\n")]
        public string GcxSettings1 {
            get {
                return ((string)(this["GcxSettings1"]));
            }
            set {
                this["GcxSettings1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<gcxDocument version=\"17.0\">\r\n  <gcxData>\r\n    <GCXCTRL sizeExtent_x=\"13414\" size" +
            "Extent_y=\"10345\" designTimeSaved=\"0\" graphLayers=\"1\"/>\r\n    <GRAPH_GDI state=\"0\"" +
            " viewports=\"1\" major_h=\"1\" major_v=\"1\" minor_h=\"0\" minor_v=\"0\">\r\n      <cursor n" +
            "ame=\"Main\" visible=\"1\" active=\"1\" align=\"1\" color=\"4718664\" hot=\"0\" style=\"0\" co" +
            "lor2=\"16777215\"/>\r\n      <Main horizontal_line=\"1\" tacho_identification=\"1\"/>\r\n " +
            "     <cursor name=\"Delta\" visible=\"0\" active=\"0\" align=\"1\" color=\"65535\" hot=\"0\"" +
            " style=\"0\" color2=\"16777215\"/>\r\n      <Delta tacho_identification=\"1\"/>\r\n      <" +
            "cursor name=\"Reference\" visible=\"0\" active=\"0\" align=\"1\" color=\"2263842\" hot=\"0\"" +
            " style=\"0\" color2=\"16777215\"/>\r\n      <Reference horizontal_line=\"1\" tacho_ident" +
            "ification=\"1\"/>\r\n      <cursor name=\"Marker1\" visible=\"0\" active=\"0\" align=\"1\" c" +
            "olor=\"5275647\" hot=\"0\" style=\"0\" color2=\"16777215\"/>\r\n      <cursor name=\"Marker" +
            "2\" visible=\"0\" active=\"0\" align=\"1\" color=\"17919\" hot=\"0\" style=\"0\" color2=\"1677" +
            "7215\"/>\r\n      <cursor name=\"Harmonic\" visible=\"0\" active=\"0\" align=\"1\" color=\"2" +
            "237106\" hot=\"0\" style=\"0\" color2=\"16777215\"/>\r\n      <Harmonic show_all_frequenc" +
            "ies=\"1\" harmonic_count=\"10\"/>\r\n      <cursor name=\"Sideband\" visible=\"0\" active=" +
            "\"0\" align=\"1\" color=\"3618615\" hot=\"0\" style=\"0\" color2=\"16777215\"/>\r\n      <curs" +
            "or name=\"TagCursor\" visible=\"0\" active=\"0\" align=\"1\" color=\"14822282\" hot=\"0\" st" +
            "yle=\"0\" color2=\"16777215\"/>\r\n      <TagCursor NextUniqueID=\"1001\" SearchSensitiv" +
            "ity=\"1.5\" SearchHalfWidth=\"9\" SearchMaximumExtremaCountWanted=\"0\" LevelFilterEna" +
            "bled=\"0\" LevelFilterValue=\"0\" TagsortMode=\"1\" TagCursorInfoListCount=\"0\"/>\r\n    " +
            "  <view name=\"Default area\" state=\"16\" header=\"0\" text=\"static text\" complexEnab" +
            "led=\"0\" secondaryViewportEnabled=\"0\" secondaryViewportAtBottom=\"1\" percentageTop" +
            "Subviewport=\"50\" secondaryCoordinateIsPhase=\"0\" secondaryViewportAtBottom_IfPhas" +
            "e=\"0\" percentageTopSubviewport_IfPhase=\"30\" nyquistIsSquare=\"0\"/>\r\n    </GRAPH_G" +
            "DI>\r\n    <XAXIS state=\"0\" unit=\"\" title=\"\" type=\"0\" zoomStart=\"0\" zoomStop=\"1000" +
            "00\" min=\"0\" max=\"1\" tickstep=\"0\" fixticks=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=" +
            "\"3\" trailingZeros=\"0\" numFormat=\"1\" minorTicks=\"0\"/>\r\n    <YAXIS state=\"0\" unit=" +
            "\"\" title=\"\" type=\"5\" zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" t" +
            "ickstepSecondary=\"30\" fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"" +
            "20\" useNice=\"1\" activeOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZer" +
            "os=\"0\" numFormat=\"1\" secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\"" +
            " secondaryLockMin=\"0\" secondaryLockMax=\"0\"/>\r\n    <YAXIS_2 state=\"17\" unit=\"\" ti" +
            "tle=\"\" type=\"5\" zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickst" +
            "epSecondary=\"30\" fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" u" +
            "seNice=\"1\" activeOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0" +
            "\" numFormat=\"1\" secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" seco" +
            "ndaryLockMin=\"0\" secondaryLockMax=\"0\"/>\r\n    <YAXIS_3 state=\"17\" unit=\"\" title=\"" +
            "\" type=\"5\" zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSec" +
            "ondary=\"30\" fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNic" +
            "e=\"1\" activeOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" num" +
            "Format=\"1\" secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondary" +
            "LockMin=\"0\" secondaryLockMax=\"0\"/>\r\n    <YAXIS_4 state=\"17\" unit=\"\" title=\"\" typ" +
            "e=\"5\" zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondar" +
            "y=\"30\" fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\"" +
            " activeOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numForma" +
            "t=\"1\" secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockM" +
            "in=\"0\" secondaryLockMax=\"0\"/>\r\n    <YAXIS_5 state=\"17\" unit=\"\" title=\"\" type=\"5\"" +
            " zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30" +
            "\" fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" acti" +
            "veOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\"" +
            " secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0" +
            "\" secondaryLockMax=\"0\"/>\r\n    <YAXIS_RIGHT1 state=\"0\" unit=\"\" title=\"\" type=\"5\" " +
            "zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30\"" +
            " fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" activ" +
            "eOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\" " +
            "secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0\"" +
            " secondaryLockMax=\"0\"/>\r\n    <YAXIS_RIGHT2 state=\"17\" unit=\"\" title=\"\" type=\"5\" " +
            "zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30\"" +
            " fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" activ" +
            "eOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\" " +
            "secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0\"" +
            " secondaryLockMax=\"0\"/>\r\n    <YAXIS_RIGHT3 state=\"17\" unit=\"\" title=\"\" type=\"5\" " +
            "zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30\"" +
            " fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" activ" +
            "eOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\" " +
            "secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0\"" +
            " secondaryLockMax=\"0\"/>\r\n    <YAXIS_RIGHT4 state=\"17\" unit=\"\" title=\"\" type=\"5\" " +
            "zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30\"" +
            " fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" activ" +
            "eOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\" " +
            "secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0\"" +
            " secondaryLockMax=\"0\"/>\r\n    <YAXIS_RIGHT5 state=\"17\" unit=\"\" title=\"\" type=\"5\" " +
            "zoomStart=\"0\" zoomStop=\"100000\" tickstep=\"0\" fixticks=\"0\" tickstepSecondary=\"30\"" +
            " fixticksSecondary=\"0\" min=\"0\" maxabs=\"1\" range=\"4\" scale=\"20\" useNice=\"1\" activ" +
            "eOnly=\"0\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\" " +
            "secondaryMin=\"-200\" secondaryMax=\"200\" secondaryIsPhase=\"1\" secondaryLockMin=\"0\"" +
            " secondaryLockMax=\"0\"/>\r\n    <ZAXIS state=\"0\" unit=\"\" title=\"\" type=\"0\" zoomStar" +
            "t=\"0\" zoomStop=\"100000\" min=\"-1\" max=\"1\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" t" +
            "railingZeros=\"0\" numFormat=\"1\"/>\r\n    <ZAXIS_2 state=\"17\" unit=\"\" title=\"\" type=" +
            "\"0\" zoomStart=\"0\" zoomStop=\"100000\" min=\"-1\" max=\"1\" lockMin=\"0\" lockMax=\"0\" num" +
            "Digits=\"3\" trailingZeros=\"0\" numFormat=\"1\"/>\r\n    <ZAXIS_3 state=\"17\" unit=\"\" ti" +
            "tle=\"\" type=\"0\" zoomStart=\"0\" zoomStop=\"100000\" min=\"-1\" max=\"1\" lockMin=\"0\" loc" +
            "kMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\"/>\r\n    <ZAXIS_4 state=\"17" +
            "\" unit=\"\" title=\"\" type=\"0\" zoomStart=\"0\" zoomStop=\"100000\" min=\"-1\" max=\"1\" loc" +
            "kMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\"/>\r\n    <ZAXIS" +
            "_5 state=\"17\" unit=\"\" title=\"\" type=\"0\" zoomStart=\"0\" zoomStop=\"100000\" min=\"-1\"" +
            " max=\"1\" lockMin=\"0\" lockMax=\"0\" numDigits=\"3\" trailingZeros=\"0\" numFormat=\"1\"/>" +
            "\r\n    <TITLE/>\r\n    <OVERALL state=\"0\"/>\r\n    <READOUT state=\"0\" pos=\"0.761364\" " +
            "hideNA=\"1\" allFunctions=\"0\" fullScreen=\"0\" hideSplitter=\"0\">\r\n      <DISPSETUP>\r" +
            "\n        <attr name=\"Cursor values\" isUserText=\"1\" isTagVector=\"0\" bold=\"1\" ital" +
            "ic=\"0\" unique=\"0\"/>\r\n        <attr name=\"X: \" unit=\"xAxis\" isUserText=\"0\" isTagV" +
            "ector=\"0\" bold=\"0\" italic=\"0\" unique=\"0\" key=\"1\"/>\r\n        <attr name=\"Y: \" uni" +
            "t=\"yAxis\" isUserText=\"0\" isTagVector=\"0\" bold=\"0\" italic=\"0\" unique=\"0\" key=\"2\"/" +
            ">\r\n        <attr name=\"Z: \" unit=\"zAxis\" isUserText=\"0\" isTagVector=\"0\" bold=\"0\"" +
            " italic=\"0\" unique=\"0\" key=\"3\"/>\r\n        <attr name=\"y: \" unit=\"yAxis\" isUserTe" +
            "xt=\"0\" isTagVector=\"0\" bold=\"0\" italic=\"0\" unique=\"0\" key=\"32\"/>\r\n        <attr " +
            "name=\"Data Quality : \" attrName=\"Data Quality\" groupName=\"Status\" groupType=\"BKI" +
            "ndexAttributeGroup\" isUserText=\"0\" isTagVector=\"0\" bold=\"0\" italic=\"0\" unique=\"0" +
            "\" dir=\"2\"/>\r\n        <attr name=\"Channel Status : \" attrName=\"Channel Status\" gr" +
            "oupName=\"Status\" groupType=\"BKIndexAttributeGroup\" isUserText=\"0\" isTagVector=\"0" +
            "\" bold=\"0\" italic=\"0\" unique=\"0\" dir=\"2\"/>\r\n      </DISPSETUP>\r\n    </READOUT>\r\n" +
            "    <LAYOUT state=\"0\" fixedId=\"{00000000-0000-0000-0000-000000000000}\" mode=\"1\"/" +
            ">\r\n    <STRFORMAT state=\"0\"/>\r\n    <LEGEND state=\"0\">\r\n      <DISPSETUP>\r\n      " +
            "  <attr attrName=\"title\" groupName=\"Buffers\" groupType=\"BKBuffersAttributeGroup\"" +
            "/>\r\n        <attr attrName=\"name\" groupName=\"Analyzer\" groupType=\"BKAnalyzerAttr" +
            "ibuteGroup\"/>\r\n        <body style=\"19\" delimiter=\" \\ \" moved=\"0\"/>\r\n        <fp" +
            "os x=\"0\" y=\"0\" cx=\"0\" cy=\"0\"/>\r\n      </DISPSETUP>\r\n    </LEGEND>\r\n    <REGION_S" +
            "ELECTOR state=\"0\" enabled=\"0\" left=\"0.3\" right=\"0.7\" low=\"0.7\" high=\"0.3\" format" +
            "=\"3\" commandVisibility=\"526\"/>\r\n    <CurveSmoothing state=\"0\" progid=\"BKCurveSmo" +
            "othing.CurveSmoothing\">\r\n      <CurveSmoothing SmoothingType=\"1\" WindowType=\"1\" " +
            "SmoothingMode=\"1\" Octave=\"1\" Order=\"1\">\r\n        <Markers/>\r\n      </CurveSmooth" +
            "ing>\r\n    </CurveSmoothing>\r\n    <ReferenceCurve/>\r\n    <GCXDROP state=\"0\"/>\r\n  " +
            "</gcxData>\r\n</gcxDocument>\r\n")]
        public string GcxSettings2 {
            get {
                return ((string)(this["GcxSettings2"]));
            }
            set {
                this["GcxSettings2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int OutputSignalTypeIndex2 {
            get {
                return ((int)(this["OutputSignalTypeIndex2"]));
            }
            set {
                this["OutputSignalTypeIndex2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("515")]
        public decimal OutputFrequency2 {
            get {
                return ((decimal)(this["OutputFrequency2"]));
            }
            set {
                this["OutputFrequency2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public decimal OutputAmplitude2 {
            get {
                return ((decimal)(this["OutputAmplitude2"]));
            }
            set {
                this["OutputAmplitude2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BufferSizeSelectedIndex {
            get {
                return ((int)(this["BufferSizeSelectedIndex"]));
            }
            set {
                this["BufferSizeSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Recording {
            get {
                return ((bool)(this["Recording"]));
            }
            set {
                this["Recording"] = value;
            }
        }
    }
}
